name: calgary-tree-equity
channels:
- conda-forge
dependencies:
- dask
- dask-geopandas
- geopandas
- jupyter
- scikit-learn
- black-jupyter
- rasterio 
- pystac-client 
- planetary-computer 
- matplotlib

